In [45]:
import numpy as np
import math

In [46]:
p11 = 4/math.sqrt(1196)
p12 = 10/math.sqrt(1196)
p13 = -24/math.sqrt(1196)
p14 = 6/math.sqrt(1196)
p15 = -12/math.sqrt(1196)
p16 = 18/math.sqrt(1196)

p21 = -9/math.sqrt(299)
p22 = 6/math.sqrt(299)
p23 = -3/math.sqrt(299)
p24 = -12/math.sqrt(299)
p25 = 5/math.sqrt(299)
p26 = 2/math.sqrt(299)

p31 = 792/math.sqrt(7998848)
p32 = 1440/math.sqrt(7998848)
p33 = 1112/math.sqrt(7998848)
p34 = 656/math.sqrt(7998848)
p35 = 1440/math.sqrt(7998848)
p36 = 1248/math.sqrt(7998848)



p = np.array([[p11, p12, p13, p14, p15, p16], [p21, p22, p23, p24, p25, p26], [p31, p32, p33, p34, p35, p36]])

print(p)

[[ 0.11566299  0.28915747 -0.69397792  0.17349448 -0.34698896  0.52048344]
 [-0.52048344  0.34698896 -0.17349448 -0.69397792  0.28915747  0.11566299]
 [ 0.28003445  0.50915354  0.39317968  0.23194773  0.50915354  0.4412664 ]]


In [47]:
print(p.T.shape)

(6, 3)


In [48]:
print(p[0].transpose().shape)

(6,)


In [49]:
t11 = 2
t12 = 3
t13 = 4

t21 = 7
t22 = 8
t23 = 9

t31 = 13
t32 = 14
t33 = 15

t = np.array([[t11, t12, t13], [t21, t22, t23], [t31, t32, t33]])

print(t)

[[ 2  3  4]
 [ 7  8  9]
 [13 14 15]]


In [50]:
print(t.shape)

(3, 3)


In [51]:
print(t[0].shape)

(3,)


In [52]:
print(t[0])
print(p[0])
print(t[0].shape)
print(p[0].shape)
# w1 = np.dot(t[0], p[0].T)
# print(w1)

[2 3 4]
[ 0.11566299  0.28915747 -0.69397792  0.17349448 -0.34698896  0.52048344]
(3,)
(6,)


In [53]:
w1 = np.outer(t[0] , p[0])
print(w1)

[[ 0.23132597  0.57831493 -1.38795584  0.34698896 -0.69397792  1.04096688]
 [ 0.34698896  0.8674724  -2.08193376  0.52048344 -1.04096688  1.56145032]
 [ 0.46265195  1.15662986 -2.77591167  0.69397792 -1.38795584  2.08193376]]


In [55]:
w = np.zeros((3, 6))

for i in range(len(p)):
    w = np.round(w + np.outer(t[i], p[i]), 4)  # Use outer product instead of dot product

print(w)

[[ 0.2283  9.6262  2.5088 -1.4955  7.9491  7.5871]
 [ 0.1036 10.7715  2.0346 -1.784   8.4004  8.6645]
 [-0.0212 11.9168  1.5603 -2.0726  8.8517  9.7419]]
