In [45]:
import numpy as np
import math

## Set Parameter

In [46]:
x1 = np.array([0, 1, 2, 3, 4])
print(x1)
x2 = x1**2
x3 = x1**3
x4 = x1**4
# x2 = np.array([1, 1, 3, 3, 5])
# print(x2)
# x3 = np.array([1, 3, 5, 7, 9])
# print(x3)

y = np.array([2, 5, 1, 8, 3])
print(y)

value = 1 
bias = np.full(len(x1), value)
print(bias)

[0 1 2 3 4]
[2 5 1 8 3]
[1 1 1 1 1]


# Formular Require
# y = a0 + a1x + a2x^2 + a3x^3 + a4x^4

## Set New column Stack

In [47]:
new_column_stack = np.column_stack((x1, x2, x3, x4, bias))

print(len(new_column_stack))

5


## Func to cal parameter c

In [48]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

## Func to cal parameter h

In [49]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

## Func to cal parameter R

In [50]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

## Func to cal parameter a ... an

In [51]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [52]:
c = np.round(cal_c_value(y), 2)
print(f"c : {c}")
# print(c)

h = np.round(cal_h_value(y, new_column_stack), 2)
print(f"h : {h}")
# print(h)

R = np.round(cal_R_value(new_column_stack), 2)
print("R :")
print(R)

a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

c : 20.6
h : [  8.6  25.8  84.2 287.4   3.8]
R :
[[6.00000e+00 2.00000e+01 7.08000e+01 2.60000e+02 2.00000e+00]
 [2.00000e+01 7.08000e+01 2.60000e+02 9.78000e+02 6.00000e+00]
 [7.08000e+01 2.60000e+02 9.78000e+02 3.74000e+03 2.00000e+01]
 [2.60000e+02 9.78000e+02 3.74000e+03 1.44708e+04 7.08000e+01]
 [2.00000e+00 6.00000e+00 2.00000e+01 7.08000e+01 1.00000e+00]]
a :
[ 22.75 -31.29  13.25  -1.71   2.  ]


In [53]:


for row in R:
    for num in row:
        print(f"{num:.5f}", end=" ")
    print()


6.00000 20.00000 70.80000 260.00000 2.00000 
20.00000 70.80000 260.00000 978.00000 6.00000 
70.80000 260.00000 978.00000 3740.00000 20.00000 
260.00000 978.00000 3740.00000 14470.80000 70.80000 
2.00000 6.00000 20.00000 70.80000 1.00000 
