In [33]:
import numpy as np

## Set Parameter

In [34]:
# x1 = np.array([0, 4000, 6000, 10000])
# print(x1)
x1 = np.array([0, 10, 20, 30])
print(x1)
x2 = np.array([0, 0.1, 0.4, 0.5])
print(x2)

y = np.array([0, 4000, 6000, 10000])
print(y)

value = 1 
bias = np.full(len(x1), value)
print(bias)

[ 0 10 20 30]
[0.  0.1 0.4 0.5]
[    0  4000  6000 10000]
[1 1 1 1]


## Set New column Stack

In [35]:
new_column_stack = np.column_stack((x1, x2))

print(len(new_column_stack))

4


## Func to cal parameter c

In [36]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

## Func to cal parameter h

In [37]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

## Func to cal parameter R

In [38]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

## Func to cal parameter a ... an

In [39]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [40]:
c = np.round(cal_c_value(y), 2)
print(f"c : {c}")
# print(c)

h = np.round(cal_h_value(y, new_column_stack), 2)
print(f"h : {h}")
# print(h)

R = cal_R_value(new_column_stack)
print("R :")
print(R)

a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

c : 38000000.0
h : [115000.   1950.]
R :
[[3.50e+02 6.00e+00]
 [6.00e+00 1.05e-01]]
a :
[   500. -10000.]


In [41]:
for row in R:
    for num in row:
        print(f"{num:.5f}", end=" ")
    print()

350.00000 6.00000 
6.00000 0.10500 
