In [9]:
import numpy as np

## Set Parameter

In [10]:
x1 = np.array([-2, -1, 0, 1, 2, 4, -4, -3, 5])
print(x1)
x2 = np.array([-4, -2, -1, -3, 2, -4, 5, 8, 0])
print(x2)
# x3 = np.array([1, 3, 5, 7, 9])
# print(x3)
x1_pow2 = x1**2
x2_pow2 = x2**2
x1x2 = x1*x2


y = np.array([16, 2, 3.5, 10.5, 38, 34, 39.5, 104, 56])
print(y)

value = 1 
bias = np.full(len(x1), value)
print(bias)

[-2 -1  0  1  2  4 -4 -3  5]
[-4 -2 -1 -3  2 -4  5  8  0]
[ 16.    2.    3.5  10.5  38.   34.   39.5 104.   56. ]
[1 1 1 1 1 1 1 1 1]


# Formular Require
# y = 1/2ax1^2 + 1/2a3x2^2 + a2x1x2 + d1x1 + d2x2
# For set column stack

## Set New column Stack

In [11]:
new_column_stack = np.column_stack((x1_pow2, x2_pow2, x1x2, x1, x2, bias))

print(len(new_column_stack))

print(new_column_stack)

9
[[  4  16   8  -2  -4   1]
 [  1   4   2  -1  -2   1]
 [  0   1   0   0  -1   1]
 [  1   9  -3   1  -3   1]
 [  4   4   4   2   2   1]
 [ 16  16 -16   4  -4   1]
 [ 16  25 -20  -4   5   1]
 [  9  64 -24  -3   8   1]
 [ 25   0   0   5   0   1]]


## Func to cal parameter c

In [12]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

## Func to cal parameter h

In [13]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

## Func to cal parameter R

In [14]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

## Func to cal parameter a ... an

In [15]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [16]:
c = np.round(cal_c_value(y), 2)
print(f"c : {c}")
# print(c)

h = np.round(cal_h_value(y, new_column_stack), 2)
print(f"h : {h}")
# print(h)

R = np.round(cal_R_value(new_column_stack), 2)
print("R :")
print(R)

a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

c : 2054.97
h : [ 4.1561e+02  9.6683e+02 -3.9750e+02 -1.7000e-01  9.6280e+01  3.3720e+01]
R :
[[ 1.3911e+02  1.4722e+02 -8.2780e+01  1.0890e+01  8.3300e+00  8.4400e+00]
 [ 1.4722e+02  5.9411e+02 -2.4078e+02 -2.7440e+01  5.3440e+01  1.5440e+01]
 [-8.2780e+01 -2.4078e+02  1.4722e+02  8.3300e+00 -2.7440e+01 -5.4400e+00]
 [ 1.0890e+01 -2.7440e+01  8.3300e+00  8.4400e+00 -5.4400e+00  2.2000e-01]
 [ 8.3300e+00  5.3440e+01 -2.7440e+01 -5.4400e+00  1.5440e+01  1.1000e-01]
 [ 8.4400e+00  1.5440e+01 -5.4400e+00  2.2000e-01  1.1000e-01  1.0000e+00]]
a :
[1.   1.5  1.   5.   4.01 6.08]


In [17]:
for row in R:
    for num in row:
        print(f"{num:.5f}", end=" ")
    print()

139.11000 147.22000 -82.78000 10.89000 8.33000 8.44000 
147.22000 594.11000 -240.78000 -27.44000 53.44000 15.44000 
-82.78000 -240.78000 147.22000 8.33000 -27.44000 -5.44000 
10.89000 -27.44000 8.33000 8.44000 -5.44000 0.22000 
8.33000 53.44000 -27.44000 -5.44000 15.44000 0.11000 
8.44000 15.44000 -5.44000 0.22000 0.11000 1.00000 
