In [53]:
import numpy as np

## Set Parameter

In [54]:
x1 = np.array([1, 1, 1, 3, 5])
print(x1)
x2 = np.array([1, 1, 3, 3, 5])
print(x2)
x3 = np.array([1, 3, 5, 7, 9])
print(x3)

y = np.array([0.1, -7.8, -6.1, -9.7, -4.2])
print(y)

value = 1 
bias = np.full(len(x1), value)
print(bias)

[1 1 1 3 5]
[1 1 3 3 5]
[1 3 5 7 9]
[ 0.1 -7.8 -6.1 -9.7 -4.2]
[1 1 1 1 1]


## Set New column Stack

In [59]:
new_column_stack = np.column_stack((x1, x2, x3, bias))

print(len(new_column_stack))

5


## Func to cal parameter c

In [56]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

## Func to cal parameter h

In [57]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

## Func to cal parameter R

In [75]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

## Func to cal parameter a ... an

In [91]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [99]:
c = np.round(cal_c_value(y), 2)
print(f"c : {c}")
# print(c)

h = np.round(cal_h_value(y, new_column_stack), 2)
print(f"h : {h}")
# print(h)

R = np.round(cal_R_value(new_column_stack), 2)
print("R :")
print(R)

a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

c : 41.96
h : [-12.78 -15.22 -31.9   -5.54]
R :
[[ 7.4  7.8 15.   2.2]
 [ 7.8  9.  17.   2.6]
 [15.  17.  33.   5. ]
 [ 2.2  2.6  5.   1. ]]
a :
[ 2.03  4.67 -3.87 -2.78]
