In [23]:
import numpy as np

In [24]:
p1 = np.array([1, 1, 1, 1])
p2 = np.array([2, 4, 8, 16])
p3 = np.array([3, 9, 27, 81])
p4 = np.array([4, 16, 64, 256])

t1 = np.array([20])
t2 = np.array([30])
t3 = np.array([50])
t4 = np.array([80])

In [30]:
P = np.array([p1, p2, p3, p4])
P = P.T
print(P)


[[  1   2   3   4]
 [  1   4   9  16]
 [  1   8  27  64]
 [  1  16  81 256]]


In [31]:
T = np.array([t1, t2, t3, t4])
T = T.T

print(T)

[[20 30 50 80]]


In [32]:
PT = P.transpose()

print(PT)

[[  1   1   1   1]
 [  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]]


In [40]:
w = np.round(np.dot(np.dot(T, np.linalg.inv(np.dot(PT, P))), PT), 3)
print(w)

[[ 36.667 -24.167   8.333  -0.833]]


In [48]:
w1 = np.dot(w,PT[0])
print(w1)

[20.]


In [55]:
w_history = np.array([])
for i in range(len(P)):
    w_history = np.round(np.append(w_history, np.dot(w, PT[i])), 2)
    print(f"wp{i} : {w_history[i]}")
print(w_history)
print(w_history.shape)

wp0 : 20.0
wp1 : 30.0
wp2 : 50.02
wp3 : 80.06
[20.   30.   50.02 80.06]
(4,)


In [53]:
for i in range(len(w_history)):
    print(f"wp{i} : {w_history[i]}")

wp0 : 20.0
wp1 : 30.0
wp2 : 50.02
wp3 : 80.06
