In [1]:
import numpy as np

In [9]:
k_1 = np.array([2, 5, -3])
xk = np.array([0, 4, 13.62, 6.32])

## Function for cal c, h, R, a

In [ ]:
# function cal c parameter
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

# function cal h parameter
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

# function cal R parameter
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

# function cal a parameter
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [6]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

In [17]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

In [26]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

In [28]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

## Cal C parameter

In [10]:
xk_cal_c = xk[1:]
print("delete first index of xk")
print(xk_cal_c)

c = np.round(cal_c_value(xk_cal_c), 2)
print(f"c : {c}")


delete first index of xk
[ 4.   13.62  6.32]
c : 80.48


## Cal h parameter

In [25]:
xk_cal_h = xk[:-1]
print("delete last index of xk")
print(xk_cal_h)
new_colum_stack = np.column_stack((uk, xk_cal_h)) # Use this for stack new colums
print("new stack data for cal h value")
print(new_colum_stack)
print(f"len of new stack {len(new_colum_stack)}")
print("\n")

h = np.round(cal_h_value(xk_cal_c, new_colum_stack), 2)
print(f"h : {h}")


delete last index of xk
[ 0.    4.   13.62]
new stack data for cal h value
[[ 2.    0.  ]
 [ 5.    4.  ]
 [-3.   13.62]]
len of new stack 3


h : [19.05 46.85]


## Cal R Parameter

In [27]:
R = np.round(cal_R_value(new_colum_stack), 2)
print("R :")
print(R)

R :
[[12.67 -6.95]
 [-6.95 67.17]]


## Cal a parameter

In [29]:
a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

a :
[2.  0.9]
