In [64]:
import numpy as np

## Set Parameter

In [65]:
k_1 = np.array([-1,0,1,2,3,4])
# print(len(x))
# print(x)
k_2 = np.array([-2,-1,0,1,2,3])
# print(y)
y = np.array([10, 5, 4.5, 3.25, 2.53, 1.91])
# print(z)

# f = np.array([8, 15, 19, 23, 17, 21, 25, 19, 23, 27])
# print(f)

value = 1 
bias = np.full(len(y), value)
print(bias)

[1 1 1 1 1 1]


## Set New column Stack

In [66]:
new_column_stack = np.column_stack((k_1,k_2))

print(len(new_column_stack))

print(new_column_stack)

6
[[-1 -2]
 [ 0 -1]
 [ 1  0]
 [ 2  1]
 [ 3  2]
 [ 4  3]]


## Func to cal parameter c

In [67]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

## Func to cal parameter h

In [68]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

## Func to cal parameter R

In [69]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

## Func to cal parameter a ... an

In [70]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [71]:
c = np.round(cal_c_value(y), 2)
print(f"c : {c}")
# print(c)

h = np.round(cal_h_value(y, new_column_stack), 2)
print(f"h : {h}")
# print(h)

R = np.round(cal_R_value(new_column_stack), 2)
print("R :")
print(R)

a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

c : 27.64
h : [ 2.7  -1.83]
R :
[[5.17 3.67]
 [3.67 3.17]]
a :
[ 5.23 -6.63]


## quadratic parameter set parameter

In [72]:
learning_rate = np.array([0.05])

a_test = np.array([0, 0, 0, 0, 0, 0]) # a start parameter 

quad_column_stack = np.column_stack((k_1,k_2,y)) # sort quadratic
print(quad_column_stack)

print(quad_column_stack[0])
print(new_column_stack[0])

[[-1.   -2.   10.  ]
 [ 0.   -1.    5.  ]
 [ 1.    0.    4.5 ]
 [ 2.    1.    3.25]
 [ 3.    2.    2.53]
 [ 4.    3.    1.91]]
[-1. -2. 10.]
[-1 -2]


In [73]:
print(a_test)
print(new_column_stack[0])

e = y[0]- (np.dot(a_test, new_column_stack[0]))

print(e)

w11 = a_test + 2 * learning_rate * np.dot(e, new_column_stack[0])

print(w11)


[0 0 0 0 0 0]
[-1 -2]


ValueError: shapes (6,) and (2,) not aligned: 6 (dim 0) != 2 (dim 0)

In [ ]:
for i in range(len(y)):
    print(f"---------- ITERATION {i+1} ----------")
    print(f"present : {quad_column_stack[i]}")
    e = np.round(y[i]- (np.dot(a_test, new_column_stack[i])), 3)
    print(f"when f {y[i]} :")
    print(f"f = {np.dot(a_test.T, new_column_stack[i])}")
    w = np.round(a_test + 2 * learning_rate * np.dot(e, new_column_stack[i]), 3)
    
    a_test = w
    
    
    print(f"error {i+1} (when f = {y[i]}): {e}")
    print(f"weight {i+1} : ")
    print(w)

---------- ITERATION 1 ----------


NameError: name 'quad_column_stack' is not defined

## MPL 

In [ ]:
a_d = np.array([0, 0])
w_t = np.array([0, 0])
y = np.dot(a, a_d)
e = k_1[0]-y
w_a = w_t+np.dot(2*e,k_1[0])

w_t = w_a

print(y)
print(e)
print(w_a)

0.0
-1.0
[2. 2.]


In [75]:
a_d = np.array([0, 0])
w_t = np.array([0, 0])
for i in range((len(k_1))):
    y = np.dot(a, a_d)
    e = k_1[i]-y
    w_a = w_t+np.dot(2*0.01*e,k_1[i])

    w_t = w_a

    print(y)
    print(f"eeror {e}")
    print(e)
    
    print(w_a)

0.0
eeror -1.0
-1.0
[0.02 0.02]
0.0
eeror 0.0
0.0
[0.02 0.02]
0.0
eeror 1.0
1.0
[0.04 0.04]
0.0
eeror 2.0
2.0
[0.12 0.12]
0.0
eeror 3.0
3.0
[0.3 0.3]
0.0
eeror 4.0
4.0
[0.62 0.62]
