In [16]:
import numpy as np

In [17]:
p1 = np.array([1,1,1,1,1,
               1,-1,-1,-1,1,
               1,1,1,1,1,
               1,-1,-1,-1,1,
               1,-1,-1,-1,1])

print(len(p1))
p2 = np.array([1,1,1,1,1,
               1,-1,-1,-1,-1,
               1,1,1,1,1,
               1,-1,-1,-1,-1,
               1,1,1,1,1])

p3 = np.array([-1,-1,1,-1,-1,
               -1,-1,1,-1,-1,
               -1,-1,1,-1,-1,
               -1,-1,1,-1,-1,
               -1,-1,1,-1,-1,])

p4 = np.array([1,1,1,1,1,
               1,-1,-1,-1,1,
               1,-1,-1,-1,1,
               1,-1,-1,-1,1,
               1,1,1,1,1])

p5 = np.array([1,-1,-1,-1,1,
               1,-1,-1,-1,1,
               1,-1,-1,-1,1,
               1,-1,-1,-1,1,
               1,1,1,1,1])
# p4 = np.array([4, 16, 64, 256])

t1 = np.array([65])
t2 = np.array([69])
t3 = np.array([73])
t4 = np.array([79])
t5 = np.array([85 ])
# t4 = np.array([80])

print(f"size of p : {len(p1)}")

25
size of p : 25


In [18]:
P = np.array([p1, p2, p3, p4, p5])
P = P.T
print(P)


[[ 1  1 -1  1  1]
 [ 1  1 -1  1 -1]
 [ 1  1  1  1 -1]
 [ 1  1 -1  1 -1]
 [ 1  1 -1  1  1]
 [ 1  1 -1  1  1]
 [-1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1]
 [ 1  1 -1  1  1]
 [ 1  1 -1 -1 -1]
 [ 1  1  1 -1 -1]
 [ 1  1 -1 -1 -1]
 [ 1  1 -1  1  1]
 [ 1  1 -1  1  1]
 [-1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1]
 [ 1  1 -1  1  1]
 [-1  1 -1  1  1]
 [-1  1  1  1  1]
 [-1  1 -1  1  1]
 [ 1  1 -1  1  1]]


In [19]:
T = np.array([t1, t2, t3, t4, t5])
T = T.T

print(T)

[[65 69 73 79 85]]


In [20]:
PT = P.transpose()

print(PT)

[[ 1  1  1  1  1  1 -1 -1 -1  1  1  1  1  1  1  1 -1 -1 -1  1  1 -1 -1 -1
   1]
 [ 1  1  1  1  1  1 -1 -1 -1 -1  1  1  1  1  1  1 -1 -1 -1 -1  1  1  1  1
   1]
 [-1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1
  -1]
 [ 1  1  1  1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1  1
   1]
 [ 1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1  1
   1]]


In [21]:
print("---------- step 2 ----------")

print(np.dot(PT, P))

print("---------- step 3 ----------")

print(np.round(np.dot(np.linalg.inv(np.dot(PT, P)),PT),3))

---------- step 2 ----------
[[25 15 -9 13  7]
 [15 25 -7 15  9]
 [-9 -7 25 -9 -7]
 [13 15 -9 25 19]
 [ 7  9 -7 19 25]]
---------- step 3 ----------
[[ 0.018 -0.008  0.016 -0.008  0.018  0.018 -0.042 -0.018 -0.042  0.076
   0.018  0.042  0.067  0.042  0.018  0.018 -0.042 -0.018 -0.042  0.076
   0.018 -0.124 -0.1   -0.124  0.018]
 [ 0.019 -0.    -0.    -0.     0.019  0.019 -0.019 -0.019 -0.019 -0.135
   0.019  0.077  0.077  0.077  0.019  0.019 -0.019 -0.019 -0.019 -0.135
   0.019  0.077  0.077  0.077  0.019]
 [-0.024 -0.032  0.065 -0.032 -0.024 -0.024 -0.073  0.024 -0.073 -0.024
  -0.024 -0.048  0.048 -0.048 -0.024 -0.024 -0.073  0.024 -0.073 -0.024
  -0.024 -0.048  0.048 -0.048 -0.024]
 [-0.014  0.161  0.177  0.161 -0.014 -0.014 -0.002  0.014 -0.002  0.063
  -0.014 -0.13  -0.114 -0.13  -0.014 -0.014 -0.002  0.014 -0.002  0.063
  -0.014  0.037  0.053  0.037 -0.014]
 [ 0.032 -0.169 -0.161 -0.169  0.032  0.032 -0.04  -0.032 -0.04   0.012
   0.032  0.006  0.014  0.006  0.032  0.032 -0.04  

In [22]:
w = np.round(np.dot(np.dot(T, np.linalg.inv(np.dot(PT, P))), PT), 3)
print(w)

[[  2.341  -4.532   6.065  -4.532   2.341   2.341 -12.938  -2.341 -12.938
   -0.082   2.341  -5.254   5.343  -5.254   2.341   2.341 -12.938  -2.341
  -12.938  -0.082   2.341  -2.92    7.677  -2.92    2.341]]


In [23]:
w1 = np.dot(w,PT[0])
print(w1)

[64.997]


In [24]:
w_history = np.array([])
for i in range(len(PT)):
    w_history = np.round(np.append(w_history, np.dot(w, PT[i])), 2)
    print(f"wp{i} : {w_history[i]}")
print(w_history)
print(w_history.shape)

wp0 : 65.0
wp1 : 69.0
wp2 : 73.0
wp3 : 79.0
wp4 : 85.0
[65. 69. 73. 79. 85.]
(5,)


In [25]:
for i in range(len(w_history)):
    print(f"wp{i} : {w_history[i]}")

wp0 : 65.0
wp1 : 69.0
wp2 : 73.0
wp3 : 79.0
wp4 : 85.0


## Test weight

In [26]:
test_weight = np.array([])
for i in range(len(PT)):
    test_weight = np.round(np.append(test_weight, np.dot(w, PT[i])), 2)
    print(test_weight[i])

65.0
69.0
73.0
79.0
85.0
