In [104]:
import numpy as np

In [105]:
p1 = np.array([1, 1, 1, 1, 1, 1 ,0])
p2 = np.array([0, 1, 1, 0, 0, 0, 0])
p3 = np.array([1, 1, 0, 1, 1, 0, 1])
p4 = np.array([1, 1, 1, 1, 0, 0, 1])
p5 = np.array([0, 1, 1, 0, 0, 1 ,1])
# p4 = np.array([4, 16, 64, 256])

t1 = np.array([0])
t2 = np.array([1])
t3 = np.array([2])
t4 = np.array([3])
t5 = np.array([4])
# t4 = np.array([80])

print(f"size of p : {len(p1)}")

size of p : 7


In [106]:
P = np.array([p1, p2, p3, p4, p5])
P = P.T
print(P)


[[1 0 1 1 0]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 0 1 1 0]
 [1 0 1 0 0]
 [1 0 0 0 1]
 [0 0 1 1 1]]


In [107]:
T = np.array([t1, t2, t3, t4, t5])
T = T.T

print(T)

[[0 1 2 3 4]]


In [108]:
PT = P.transpose()

print(PT)

[[1 1 1 1 1 1 0]
 [0 1 1 0 0 0 0]
 [1 1 0 1 1 0 1]
 [1 1 1 1 0 0 1]
 [0 1 1 0 0 1 1]]


In [109]:
print("---------- step 2 ----------")

print(np.dot(PT, P))

print("---------- step 3 ----------")

print(np.round(np.dot(np.linalg.inv(np.dot(PT, P)),PT),3))

---------- step 2 ----------
[[6 2 4 4 3]
 [2 2 1 2 2]
 [4 1 5 4 2]
 [4 2 4 5 3]
 [3 2 2 3 4]]
---------- step 3 ----------
[[ 0.207 -0.172  0.172  0.207  0.172  0.414 -0.414]
 [-0.31   0.759  0.241 -0.31   0.241 -0.621 -0.379]
 [-0.138  0.448 -0.448 -0.138  0.552 -0.276  0.276]
 [ 0.414 -0.345  0.345  0.414 -0.655 -0.172  0.172]
 [-0.241  0.034 -0.034 -0.241 -0.034  0.517  0.483]]


In [110]:
w = np.round(np.dot(np.dot(T, np.linalg.inv(np.dot(PT, P))), PT), 3)
print(w)

[[-0.31   0.759  0.241 -0.31  -0.759  0.379  2.621]]


In [111]:
w1 = np.dot(w,PT[0])
print(w1)

[0.]


In [112]:
w_history = np.array([])
for i in range(len(PT)):
    w_history = np.round(np.append(w_history, np.dot(w, PT[i])), 2)
    print(f"wp{i} : {w_history[i]}")
print(w_history)
print(w_history.shape)

wp0 : 0.0
wp1 : 1.0
wp2 : 2.0
wp3 : 3.0
wp4 : 4.0
[0. 1. 2. 3. 4.]
(5,)


In [113]:
for i in range(len(w_history)):
    print(f"wp{i} : {w_history[i]}")

wp0 : 0.0
wp1 : 1.0
wp2 : 2.0
wp3 : 3.0
wp4 : 4.0


## Test weight

In [114]:
test_weight = np.array([])
for i in range(len(PT)):
    test_weight = np.round(np.append(test_weight, np.dot(w, PT[i])), 2)
    print(test_weight[i])

0.0
1.0
2.0
3.0
4.0
