In [1]:
import numpy as np

x1 = np.array([1, 1, 1, 3, 5])
x2 = np.array([1, 1, 3, 3, 5])
x3 = np.array([1, 3, 5, 7, 9])
y = np.array([0.1, -7.8, -6.1, -9.7, -4.2])

# Reshape x1, x2, and x3 to match the specified format
n1 = np.vstack((x1, np.ones_like(x1)))
n2 = np.vstack((x2, np.ones_like(x2)))
n3 = np.vstack((x3, np.ones_like(x3)))

# You can also create n4 and n5 similarly
n4 = np.vstack((x1, np.ones_like(x1) * 3))
n5 = np.vstack((x2, np.ones_like(x2) * 3))

print("n1:")
print(n1)
print("n2:")
print(n2)
print("n3:")
print(n3)
print("n4:")
print(n4)
print("n5:")
print(n5)


n1:
[[1 1 1 3 5]
 [1 1 1 1 1]]
n2:
[[1 1 3 3 5]
 [1 1 1 1 1]]
n3:
[[1 3 5 7 9]
 [1 1 1 1 1]]
n4:
[[1 1 1 3 5]
 [3 3 3 3 3]]
n5:
[[1 1 3 3 5]
 [3 3 3 3 3]]


In [3]:
import numpy as np

x1 = np.array([1, 1, 1, 3, 5])
x2 = np.array([1, 1, 3, 3, 5])
x3 = np.array([1, 3, 5, 7, 9])
y = np.array([0.1, -7.8, -6.1, -9.7, -4.2])
bias = np.array([1, 1, 1, 1, 1])

value = 1
bias = np.full(len(x1), value)

n1 = np.column_stack((x1, x2, x3, bias))
n2 = np.column_stack((x1, x2, x3, np.full_like(bias, 1)))
n3 = np.column_stack((x1, x2, x3, bias))
n4 = np.column_stack((x2, x2, x3, bias))
n5 = np.column_stack((x3, x3, x3, bias))

print("n1 =", n1)
print("n2 =", n2)
print("n3 =", n3)
print("n4 =", n4)
print("n5 =", n5)


n1 = [[1 1 1 1]
 [1 1 3 1]
 [1 3 5 1]
 [3 3 7 1]
 [5 5 9 1]]
n2 = [[1 1 1 1]
 [1 1 3 1]
 [1 3 5 1]
 [3 3 7 1]
 [5 5 9 1]]
n3 = [[1 1 1 1]
 [1 1 3 1]
 [1 3 5 1]
 [3 3 7 1]
 [5 5 9 1]]
n4 = [[1 1 1 1]
 [1 1 3 1]
 [3 3 5 1]
 [3 3 7 1]
 [5 5 9 1]]
n5 = [[1 1 1 1]
 [3 3 3 1]
 [5 5 5 1]
 [7 7 7 1]
 [9 9 9 1]]


In [4]:
import numpy as np

x1 = np.array([1, 1, 1, 3, 5])
x2 = np.array([1, 1, 3, 3, 5])
x3 = np.array([1, 3, 5, 7, 9])
bias = np.array([1, 1, 1, 1, 1])

# Create new arrays
n1 = x1 * bias
n2 = x2 * bias
n3 = x3 * bias
n4 = np.maximum(x1, x2) * bias
n5 = np.maximum(x2, x3) * bias

print("n1 =", n1)
print("n2 =", n2)
print("n3 =", n3)
print("n4 =", n4)
print("n5 =", n5)


n1 = [1 1 1 3 5]
n2 = [1 1 3 3 5]
n3 = [1 3 5 7 9]
n4 = [1 1 3 3 5]
n5 = [1 3 5 7 9]


In [5]:
import numpy as np

x1 = np.array([1, 1, 1, 3, 5])
x2 = np.array([1, 1, 3, 3, 5])
x3 = np.array([1, 3, 5, 7, 9])
bias = np.array([1, 1, 1, 1, 1])

result = np.column_stack((x1, x2, x3, bias))
print(result)


[[1 1 1 1]
 [1 1 3 1]
 [1 3 5 1]
 [3 3 7 1]
 [5 5 9 1]]


In [9]:
print(result[0].shape)
print(result[0].T)
print(result[0].T.shape)


(4,)
[1 1 1 1]
(4,)
