In [2]:
import numpy as np

## Set Parameter

In [3]:
x = np.array([1, 2, 2, 3, 5])
print(x)
y = np.array([1, 3, 4, 5, 2])
print(y)
z = np.array([1, 4, 3, 10, 7])
print(z)

f = np.array([50, 100, 105, 165, 150])
print(f)

value = 1 
bias = np.full(len(x), value)
print(bias)

[1 2 2 3 5]
[1 3 4 5 2]
[ 1  4  3 10  7]
[ 50 100 105 165 150]
[1 1 1 1 1]


## Set New column Stack

In [4]:
new_column_stack = np.column_stack((x, y, z, bias))

print(len(new_column_stack))

print(new_column_stack)

5
[[ 1  1  1  1]
 [ 2  3  4  1]
 [ 2  4  3  1]
 [ 3  5 10  1]
 [ 5  2  7  1]]


## Func to cal parameter c

In [5]:
def cal_c_value(y):
    c = 1/len(y)*(sum(y**2))
    return c

## Func to cal parameter h

In [6]:
def cal_h_value(y,new_column_stack):
    a = 0
    h = 0
    for i in range(len(y)):
        a = a + y[i]*new_column_stack[i]
        
    h = (1/len(y))*a
        
    return h

## Func to cal parameter R

In [7]:
def cal_R_value(new_column_stack):
    a = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize a zero matrix of the correct size
    R = np.zeros((len(new_column_stack[0]), len(new_column_stack[0])))  # Initialize R as a zero matrix

    for i in range(len(new_column_stack)):
        a += np.outer(new_column_stack[i], new_column_stack[i])  # Compute the outer product and add it to 'a'
    
    R = (1/len(new_column_stack))*a
    
    return R

## Func to cal parameter a ... an

In [8]:
def cal_a_value(R, h):
    a = np.dot(np.linalg.inv(R), h)  # Matrix multiplication between R and h
    return a

In [9]:
c = np.round(cal_c_value(f), 2)
print(f"c : {c}")
# print(c)

h = np.round(cal_h_value(f, new_column_stack), 2)
print(f"h : {h}")
# print(h)

R = np.round(cal_R_value(new_column_stack), 2)
print("R :")
print(R)

a = np.round(cal_a_value(R, h), 2)
print("a :")
print(a)

c : 14650.0
h : [341. 379. 693. 114.]
R :
[[ 8.6  8.  16.   2.6]
 [ 8.  11.  17.8  3. ]
 [16.  17.8 35.   5. ]
 [ 2.6  3.   5.   1. ]]
a :
[15. 10.  5. 20.]
