In [1]:
import numpy as np

In [2]:
p1 = np.array([255, 0, 0])
p2 = np.array([0, 255, 0])
p3 = np.array([0, 0, 255])
# p4 = np.array([4, 16, 64, 256])

t1 = np.array([3600])
t2 = np.array([1200])
t3 = np.array([2400])
# t4 = np.array([80])

In [3]:
P = np.array([p1, p2, p3])
P = P.T
print(P)


[[255   0   0]
 [  0 255   0]
 [  0   0 255]]


In [4]:
T = np.array([t1, t2, t3])
T = T.T

print(T)

[[3600 1200 2400]]


In [6]:
PT = P.transpose()

print(PT)

[[255   0   0]
 [  0 255   0]
 [  0   0 255]]


In [7]:
w = np.round(np.dot(np.dot(T, np.linalg.inv(np.dot(PT, P))), PT), 3)
print(w)

[[14.118  4.706  9.412]]


In [8]:
w1 = np.dot(w,PT[0])
print(w1)

[3600.09]


In [9]:
w_history = np.array([])
for i in range(len(P)):
    w_history = np.round(np.append(w_history, np.dot(w, PT[i])), 2)
    print(f"wp{i} : {w_history[i]}")
print(w_history)
print(w_history.shape)

wp0 : 3600.09
wp1 : 1200.03
wp2 : 2400.06
[3600.09 1200.03 2400.06]
(3,)


In [10]:
for i in range(len(w_history)):
    print(f"wp{i} : {w_history[i]}")

wp0 : 3600.09
wp1 : 1200.03
wp2 : 2400.06


## Test input

In [11]:
ptest = np.array([0, 100, 100])
ptestT = ptest.transpose()
wtest = np.dot(w,ptestT)
print(wtest)

[1411.8]
