In [1]:
import numpy as np

In [3]:
# class 1 [1 0 0]
p1 = np.array([10, 10, 10])
p2 = np.array([10.5, 9.8, 9.6])
p3 = np.array([9.7, 10.3, 10.2])

# class 2 [0 1 0]
p4 = np.array([5, -15, 0])
p5 = np.array([4.7, -14.8, 0.3])

# class 1 [1 0 0]
p6 = np.array([-20, -20, -20])
p7 = np.array([-19.6, -20.2, -20.3])
p8 = np.array([-20.3, -19.5, -19.1])

# class 3 [0 0 1]
p9 = np.array([-5, 20, -15])
p10 = np.array([-4.8, 19.7, -15.4])
p11 = np.array([15, 15, 15])
p12 = np.array([15.4, 14.7, 14.9])


In [4]:
print(len(p1))

3


In [14]:
new_stack_w1 = np.array([p1, p2, p3])
print(new_stack_w1)

w = np.zeros(len(new_stack_w1))


for i in range(len(new_stack_w1)):
    current_array = new_stack_w1[i]
    print(current_array)
    print(f"------- Iteration {i} -------")
    w = w + new_stack_w1[i]
    print(w)


[[10.  10.  10. ]
 [10.5  9.8  9.6]
 [ 9.7 10.3 10.2]]
[10. 10. 10.]
------- Iteration 0 -------
[10. 10. 10.]
[10.5  9.8  9.6]
------- Iteration 1 -------
[20.5 19.8 19.6]
[ 9.7 10.3 10.2]
------- Iteration 2 -------
[30.2 30.1 29.8]
