In [5]:
import numpy as np

In [6]:
# class 1 [1 0 0]
p1 = np.array([0, 7, 7])
p2 = np.array([0, 9, 9])
p3 = np.array([8,0,0])
p4 = np.array([9, 0, 0])

# class 2 [0 1 0]
p5 = np.array([7, 7, 8])
p6 = np.array([9,9,10])
p7 = np.array([0,0,1])
p8 = np.array([0,0,2])

# class 3 [0 0 1]
p9 = np.array([4,4,6])
p10 = np.array([6,6,4])


In [7]:
print(len(p1))

3


In [8]:
new_stack_w1 = np.array([p1, p2, p3])
print(new_stack_w1)

w = np.zeros(len(new_stack_w1))


for i in range(len(new_stack_w1)):
    current_array = new_stack_w1[i]
    print(current_array)
    print(f"------- Iteration {i} -------")
    w = w + new_stack_w1[i]
    print(w)


[[0 7 7]
 [0 9 9]
 [8 0 0]]
[0 7 7]
------- Iteration 0 -------
[0. 7. 7.]
[0 9 9]
------- Iteration 1 -------
[ 0. 16. 16.]
[8 0 0]
------- Iteration 2 -------
[ 8. 16. 16.]
