In [217]:
import numpy as np
from sympy import symbols, Eq, solve

In [218]:
input_p = np.array([[1,1,1,1,1],
                    [2,3,1,5,6],
                    [9,7,4,2,1],
                    [-4, -7, -3, -8, -2],
                    [-5,-9,-3,-2,-1]])

print(input_p[0])

[1 1 1 1 1]


In [219]:
w_layer1 = []

for i in range(len(input_p) - 1):
    row = input_p[i + 1] - input_p[0]
    w_layer1.append(row)

w_layer1 = abs(np.array(w_layer1))

print(w_layer1)


[[ 1  2  0  4  5]
 [ 8  6  3  1  0]
 [ 5  8  4  9  3]
 [ 6 10  4  3  2]]


In [220]:
for i in range(len(w_layer1)):
    print(w_layer1[i])

[1 2 0 4 5]
[8 6 3 1 0]
[5 8 4 9 3]
[ 6 10  4  3  2]


In [221]:
new_w_layer1 = []

for i in range(len(w_layer1)):
    new_w_layer1.append(w_layer1[i][1:])
new_w_layer1 = np.array(new_w_layer1)   
print(new_w_layer1)

[[ 2  0  4  5]
 [ 6  3  1  0]
 [ 8  4  9  3]
 [10  4  3  2]]


In [222]:
print(w_layer1[0][:1])

[1]


In [223]:
new_w_layer11 = []

for i in range(len(w_layer1)):
    new_w_layer11.append(w_layer1[i][:1])
new_w_layer11 = np.array(new_w_layer11)   
new_w_layer11 = new_w_layer11*(-1)
print(new_w_layer11)

[[-1]
 [-8]
 [-5]
 [-6]]


In [224]:
w = np.round(np.dot(np.linalg.inv(new_w_layer1), new_w_layer11),2)

print(w)

[[  4.1 ]
 [-11.58]
 [  2.13]
 [ -3.54]]


In [225]:
w = np.insert(w, 0, 1, axis=0)

w = w.flatten()

w_inv = w*(-1)

print(w)

[  1.     4.1  -11.58   2.13  -3.54]


In [226]:
# Define symbolic variable
bias = symbols('bias')

# Create the equation
eqn = Eq(np.dot(w, input_p[0]) + bias, 0)

# Solve for bias
solutions = solve(eqn, bias)
print(solutions)

test_input = np.array([1,2,3,4,5])
print(np.dot(w, test_input)+solutions)

[7.89000000000000]
[-26.8300000000000]


In [228]:
for i in range(2):
    print(f"--------- ITERATION {i} ----------")
    # Define symbolic variable
    bias = symbols('bias')

    # Create the equation
    eqn = Eq(np.dot(w, input_p[0]) + bias, 0)

    # Solve for bias
    solutions = solve(eqn, bias)
    print(solutions)

    test_input = np.array([1,2,3,4,5])
    print(np.dot(w, test_input)+solutions)
    
    w = w_inv

--------- ITERATION 0 ----------
[7.89000000000000]
[-26.8300000000000]
--------- ITERATION 1 ----------
[-7.89000000000000]
[26.8300000000000]
