In [16]:
import numpy as np

In [17]:
p1 = np.array([1, 1, 1])
p2 = np.array([-1, 1, 1])
p3 = np.array([-1, -1, 1])

t1 = np.array([100, 100])
t2 = np.array([100, 50])
t3 = np.array([100, 0])

In [18]:
P = np.array([p1, p2, p3])
P = P.T
print(P)


[[ 1 -1 -1]
 [ 1  1 -1]
 [ 1  1  1]]


In [19]:
T = np.array([t1, t2, t3])
T = T.T

print(T)

[[100 100 100]
 [100  50   0]]


In [20]:
PT = P.transpose()

print(PT)

[[ 1  1  1]
 [-1  1  1]
 [-1 -1  1]]


In [21]:
w = np.round(np.dot(np.dot(T, np.linalg.inv(np.dot(PT, P))), PT), 3)
print(w)

[[  0.   0. 100.]
 [ 25.  25.  50.]]


In [22]:
w1 = np.dot(w,PT[0])
print(w1)

[100. 100.]


In [23]:
w_history = np.array([])
for i in range(len(P)):
    w_history = np.round(np.append(w_history, np.dot(w, PT[i])), 2)
    print(f"wp{i} : {w_history[i]}")
print(w_history)
print(w_history.shape)

wp0 : 100.0
wp1 : 100.0
wp2 : 100.0
[100. 100. 100.  50. 100.   0.]
(6,)


In [24]:
for i in range(len(w_history)):
    print(f"wp{i} : {w_history[i]}")

wp0 : 100.0
wp1 : 100.0
wp2 : 100.0
wp3 : 50.0
wp4 : 100.0
wp5 : 0.0
