In [67]:
import numpy as np

In [68]:
p1 = np.array([1, 1, 1])
p2 = np.array([-1, 1, 1])
p3 = np.array([-1, -1, 1])

t1 = np.array([100, 100])
t2 = np.array([100, 50])
t3 = np.array([100, 0])

print(f"size of p : {len(p1)}")

size of p : 3


In [69]:
P = np.array([p1, p2, p3])
P = P.T
print(P)


[[ 1 -1 -1]
 [ 1  1 -1]
 [ 1  1  1]]


In [70]:
T = np.array([t1, t2, t3])
T = T.T

print(T)

[[100 100 100]
 [100  50   0]]


In [71]:
PT = P.transpose()

print(PT)

[[ 1  1  1]
 [-1  1  1]
 [-1 -1  1]]


In [72]:
print("---------- step 2 ----------")

print(np.dot(PT, P))

print("---------- step 3 ----------")

print(np.round(np.dot(np.linalg.inv(np.dot(PT, P)),PT),3))

---------- step 2 ----------
[[ 3  1 -1]
 [ 1  3  1]
 [-1  1  3]]
---------- step 3 ----------
[[ 0.5  0.   0.5]
 [-0.5  0.5  0. ]
 [ 0.  -0.5  0.5]]


In [73]:
w = np.round(np.dot(np.dot(T, np.linalg.inv(np.dot(PT, P))), PT), 3)
print(w)

[[  0.   0. 100.]
 [ 25.  25.  50.]]


In [74]:
w1 = np.dot(w,PT[0])
print(w1)

[100. 100.]


In [75]:
w_history = np.array([])
for i in range(len(PT)):
    w_history = np.round(np.append(w_history, np.dot(w, PT[i])), 2)
    print(f"wp{i} : {w_history[i]}")
print(w_history)
print(w_history.shape)

wp0 : 100.0
wp1 : 100.0
wp2 : 100.0
[100. 100. 100.  50. 100.   0.]
(6,)


In [76]:
for i in range(len(w_history)):
    print(f"wp{i} : {w_history[i]}")

wp0 : 100.0
wp1 : 100.0
wp2 : 100.0
wp3 : 50.0
wp4 : 100.0
wp5 : 0.0


## Test weight

In [77]:
input_p = np.array([[-1,-1,-1],[1,1,-1],[1,-1,-1]])

print(input_p)

[[-1 -1 -1]
 [ 1  1 -1]
 [ 1 -1 -1]]


In [81]:
test_weight = np.array([])
for i in range(len(input_p)):
    test_weight = np.round(np.append(test_weight, np.dot(w, input_p[i])), 2)
    print(np.dot(w, input_p[i]))
    

[-100. -100.]
[-100.    0.]
[-100.  -50.]
