In [115]:
import numpy as np

In [116]:
def hard_lim(x):
    if x > 0:
        return 1
    else:
        return -1

In [117]:
p = np.array([[1,-1,-1,1,-1,1,1,-1,-1,1,1,-1,1,-1,-1,1],
              [1,1,1,1,1,-1,-1,1,1,-1,-1,1,1,1,1,1],
              [1,-1,1,-1,-1,1,-1,1,1,-1,1,-1,-1,1,-1,1]])

p1 = np.array([1,-1,-1,1,-1,1,1,-1,-1,1,1,-1,1,-1,-1,1])
p2 = np.array([1,1,1,1,1,-1,-1,1,1,-1,-1,1,1,1,1,1])
p3 = np.array([1,-1,1,-1,-1,1,-1,1,1,-1,1,-1,-1,1,-1,1])

print(f"p1 : {p1}")
print(f"p2 : {p2}")
print(f"p3 : {p3}")

print(f"size of p : {len(p[0])}")

p1 : [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]
p2 : [ 1  1  1  1  1 -1 -1  1  1 -1 -1  1  1  1  1  1]
p3 : [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
size of p : 16


In [118]:
w1 = np.outer(p[0], p[0])
w2 = np.outer(p[1], p[1])
w3 = np.outer(p[2], p[2])

w = w1 + w2 + w3


# print(w1)
# print(w2)
# print(w3)

print(w)

[[ 3 -1  1  1 -1  1 -1  1  1 -1  1 -1  1  1 -1  3]
 [-1  3  1  1  3 -3 -1  1  1 -1 -3  3  1  1  3 -1]
 [ 1  1  3 -1  1 -1 -3  3  3 -3 -1  1 -1  3  1  1]
 [ 1  1 -1  3  1 -1  1 -1 -1  1 -1  1  3 -1  1  1]
 [-1  3  1  1  3 -3 -1  1  1 -1 -3  3  1  1  3 -1]
 [ 1 -3 -1 -1 -3  3  1 -1 -1  1  3 -3 -1 -1 -3  1]
 [-1 -1 -3  1 -1  1  3 -3 -3  3  1 -1  1 -3 -1 -1]
 [ 1  1  3 -1  1 -1 -3  3  3 -3 -1  1 -1  3  1  1]
 [ 1  1  3 -1  1 -1 -3  3  3 -3 -1  1 -1  3  1  1]
 [-1 -1 -3  1 -1  1  3 -3 -3  3  1 -1  1 -3 -1 -1]
 [ 1 -3 -1 -1 -3  3  1 -1 -1  1  3 -3 -1 -1 -3  1]
 [-1  3  1  1  3 -3 -1  1  1 -1 -3  3  1  1  3 -1]
 [ 1  1 -1  3  1 -1  1 -1 -1  1 -1  1  3 -1  1  1]
 [ 1  1  3 -1  1 -1 -3  3  3 -3 -1  1 -1  3  1  1]
 [-1  3  1  1  3 -3 -1  1  1 -1 -3  3  1  1  3 -1]
 [ 3 -1  1  1 -1  1 -1  1  1 -1  1 -1  1  1 -1  3]]


In [119]:
input_p = np.array([[1,1,1,-1,-1,1,1,1,1,1,1,-1,-1,1,-1,1], 
                    [1,1,1,1,1,1,-1,1,1,-1,1,1,1,1,1,1]])

print(f"size of input_p : {len(input_p[0])}")

size of input_p : 16


In [120]:
# a = np.dot(w, input_p[0])

# print(a)

# pass_hardlim = np.array([])
# for j in range(len(a)):
#     pass_hardlim = np.append(pass_hardlim, hard_lim(a[j]))

# print(pass_hardlim)

# for k in range(len(p)): ## check index
#     if np.array_equal(pass_hardlim, p[k]):
#         print(f"pass_hardlim matches p at index {k+1}")

## Loop compute input : 1

In [121]:
# p_input = input_p[0]

for i in range(2):
    print(f"---------- ITERATION {i} ----------")
    a = np.dot(w, input_p[0])

    print(a)

    pass_hardlim = np.array([])
    for j in range(len(a)):
        pass_hardlim = np.append(pass_hardlim, hard_lim(a[j]))

    print(pass_hardlim)
    
    input_p[0] = pass_hardlim

    for k in range(len(p)): ## check index
        if np.array_equal(pass_hardlim, p[k]):
            print(f"pass_hardlim matches p at index {k+1}")

---------- ITERATION 0 ----------
[ 10 -14   6 -10 -14  14  -6   6   6  -6  14 -14 -10   6 -14  10]
[ 1. -1.  1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.]
pass_hardlim matches p at index 3
---------- ITERATION 1 ----------
[ 16 -16  16 -16 -16  16 -16  16  16 -16  16 -16 -16  16 -16  16]
[ 1. -1.  1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.]
pass_hardlim matches p at index 3


In [122]:
for i in range(2):
    print(f"---------- ITERATION {i} ----------")
    a = np.dot(w, input_p[1])

    print(a)

    pass_hardlim = np.array([])
    for j in range(len(a)):
        pass_hardlim = np.append(pass_hardlim, hard_lim(a[j]))

    print(pass_hardlim)
    
    input_p[1] = pass_hardlim

    for k in range(len(p)): ## check index
        if np.array_equal(pass_hardlim, p[k]):
            print(f"pass_hardlim matches p at index {k+1}")

---------- ITERATION 0 ----------
[ 12  12  20   4  12 -12 -20  20  20 -20 -12  12   4  20  12  12]
[ 1.  1.  1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1.  1.  1.  1.]
pass_hardlim matches p at index 2
---------- ITERATION 1 ----------
[  8  24  24   8  24 -24 -24  24  24 -24 -24  24   8  24  24   8]
[ 1.  1.  1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1.  1.  1.  1.]
pass_hardlim matches p at index 2
