In [156]:
import numpy as np
import math

In [157]:
p = np.array([0, 1, 2]) # Input
t = np.array([[0, 4], [5, 0], [10, 4]]) # Target

print(t)

[[ 0  4]
 [ 5  0]
 [10  4]]


In [158]:
w_layer1 = np.array([-0.1, 0.2, 0.1, -0.2])
b_layer1 = np.array([0.1, 0.2, 0.3, 0.4])

w_layer2 = np.array([[0.1, -0.2, 0.3, -0.4],[0.4, -0.3, -0.2, 0.1]])
b_layer2 = np.array([0.1, 0.1])

print(w_layer1.shape)
print(w_layer2.shape)

(4,)
(2, 4)


## function to compute

In [159]:
def log_sigmod(a):
    return 1/(1+math.exp(1)**-a)


def get_identity(matix):
    # Create an identity matrix
    n = len(matix)
    identity_matrix = np.identity(n)

    # Define the array of values
    values = (1-matix)*matix

    # Multiply the identity matrix by the array of values element-wise
    result_matrix = identity_matrix * values

    return result_matrix

## wp+b static compute

In [160]:
# print(f"---------- when p : {p[0]} ----------")
# n1 = np.dot(w_layer1 ,p[0])+b_layer1
# n1 = np.round(log_sigmod(n1),2)
# print(f"n1 : {n1}")

# n2 = np.dot(w_layer2 ,n1.T)+b_layer2
# print(f"n2 : {n2}")
# print(n2)

# e = t[0]-n2

# print(f"e (error) : {e}")

# s_layer2 = np.array([-1, -1])
# print("s layer 2 : ")
# print(s_layer2)

# # pre_press_to_iden = (1-n1)*n1

# # print(pre_press_to_iden)

# identify_matrix = np.round(get_identity(n1), 2)
# print("Identify matrix : ")
# print(identify_matrix)

# # print(w_layer2)


# s_layer1 = np.dot(np.dot(identify_matrix, w_layer2.T), s_layer2.T)
# print("s layer 1 : ")
# print(s_layer1)


## wp + b Loop compute

In [161]:
error_history = np.array([])

for i in range(len(p)):
    print(f"---------- when p : {p[i]} ----------")
    n1 = np.dot(w_layer1 ,p[i])+b_layer1
    print(f"n1 : {n1}")
    n1 = np.round(log_sigmod(n1),2)
    print(f"n1 : {n1}")

    n2 = np.dot(w_layer2 ,n1.T)+b_layer2
    print(f"n2 : {n2}")
    print(n2)

    e = t[i]-n2
    
    error_history = np.append(error_history, e)

    print(f"e (error) : {e}")

    s_layer2 = np.array([-1, -1])
    print("s layer 2 : ")
    print(s_layer2)

    # pre_press_to_iden = (1-n1)*n1

    # print(pre_press_to_iden)

    identify_matrix = np.round(get_identity(n1), 2)
    print("Identify matrix : ")
    print(identify_matrix)

    # print(w_layer2)


    s_layer1 = np.dot(np.dot(identify_matrix, w_layer2.T), s_layer2.T)
    print("s layer 1 : ")
    print(s_layer1)
    print(" ")

---------- when p : 0 ----------
n1 : [0.1 0.2 0.3 0.4]
n1 : [0.52 0.55 0.57 0.6 ]
n2 : [-0.027  0.089]
[-0.027  0.089]
e (error) : [0.027 3.911]
s layer 2 : 
[-1 -1]
Identify matrix : 
[[0.25 0.   0.   0.  ]
 [0.   0.25 0.   0.  ]
 [0.   0.   0.25 0.  ]
 [0.   0.   0.   0.24]]
s layer 1 : 
[-0.125  0.125 -0.025  0.072]
 
---------- when p : 1 ----------
n1 : [0.  0.4 0.4 0.2]
n1 : [0.5  0.6  0.6  0.55]
n2 : [-0.01   0.055]
[-0.01   0.055]
e (error) : [ 5.01  -0.055]
s layer 2 : 
[-1 -1]
Identify matrix : 
[[0.25 0.   0.   0.  ]
 [0.   0.24 0.   0.  ]
 [0.   0.   0.24 0.  ]
 [0.   0.   0.   0.25]]
s layer 1 : 
[-0.125  0.12  -0.024  0.075]
 
---------- when p : 2 ----------
n1 : [-0.1  0.6  0.5  0. ]
n1 : [0.48 0.65 0.62 0.5 ]
n2 : [0.004 0.023]
[0.004 0.023]
e (error) : [9.996 3.977]
s layer 2 : 
[-1 -1]
Identify matrix : 
[[0.25 0.   0.   0.  ]
 [0.   0.23 0.   0.  ]
 [0.   0.   0.24 0.  ]
 [0.   0.   0.   0.25]]
s layer 1 : 
[-0.125  0.115 -0.024  0.075]
 


In [162]:
print(error_history)

[ 0.027  3.911  5.01  -0.055  9.996  3.977]


## Get Square Error 

In [163]:
sigma_e = sum(error_history**2)
print("e: square error :")
print(sigma_e)

e: square error :
156.13632
