In [72]:
import numpy as np
import sympy as sp


In [73]:
p = np.array([0, 100])
t = np.array([-30, 0])

w_layer1 = np.array([0.1, 0.3, 0.5])
b_layer1 = np.array([0.9, 0.6, 0.2])

w_layer2 = np.array([1, 2, 3])
b_layer2 = np.array([4])

learning_rate = 0.01

## sigmoid function

In [74]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [75]:
def get_a_layer1(p, w_layer1, bias):
    a_layer1 = np.zeros(len(w_layer1))
    for i in range(len(w_layer1)):
        a_layer1[i] = sigmoid(w_layer1[i]*p+bias[i])
    return a_layer1

In [76]:
def get_a_layer2(a_layer1, w_layer2, bias):
    a_layer2 = 0
    for i in range(len(w_layer2)):
        a_layer2 = a_layer2 + w_layer2[i] * a_layer1[i]
    return a_layer2+bias

In [53]:
def get_error(t, a):
    return t-a

In [54]:
def get_s_layer2(error):
    return -2*1*error    

In [55]:
def get_identity(matix):
    # Create an identity matrix
    n = len(matix)
    identity_matrix = np.identity(n)

    # Define the array of values
    values = (1-matix)*matix

    # Multiply the identity matrix by the array of values element-wise
    result_matrix = identity_matrix * values

    return result_matrix

In [56]:
def get_s_layer1(identity_matrix, w_layer2, s_layer2):
    return np.dot(identity_matrix, w_layer2.T)* s_layer2

In [57]:
def get_new_weight_layer2(old_weight_layer2, learning_rate, s_layer2, a_layer1):
    return old_weight_layer2-learning_rate*s_layer2*a_layer1.T

In [58]:
def get_new_bias_layer2(old_bias_layer2, learning_rate, s_layer2):
    return old_bias_layer2-learning_rate*s_layer2

In [59]:
def get_new_weight_layer1(old_weight_layer1, learning_rate, s_layer1):
    return old_weight_layer1-(learning_rate*s_layer1*0) # 0 is a0

In [60]:
def get_new_bias_layer1(old_bias_layer1, learning_rate, s_layer1):
    return old_bias_layer1-learning_rate*s_layer1

## Cal Patameter

In [61]:
a_layer1 = get_a_layer1(p[0], w_layer1, b_layer1)
print("s layer 1 :")
print(a_layer1)

s layer 1 :
[0.7109495  0.64565631 0.549834  ]


In [62]:
a_layer2 = get_a_layer2(a_layer1, w_layer2, b_layer2)
print("a layer 2 :")
print(a_layer2)

a layer 2 :
[7.65176411]


In [63]:
error_layer1 = get_error(t[0], a_layer2)
print("error layer 1 :")
print(error_layer1)

error layer 1 :
[-37.65176411]


In [64]:
s_layer2 = get_s_layer2(error_layer1)
print("s layer 2 :")
print(s_layer2)

s layer 2 :
[75.30352821]


In [65]:
identity_matrix = get_identity(a_layer1)
print("Identity matrix : ")
print(identity_matrix)
print("\n")

s_layer1 = get_s_layer1(identity_matrix, w_layer2, s_layer2)
print("s layer 1 :")
print(s_layer1)



Identity matrix : 
[[0.20550031 0.         0.        ]
 [0.         0.22878424 0.        ]
 [0.         0.         0.24751657]]


s layer 1 :
[15.47489819 34.45652101 55.91661365]


In [66]:
new_w_layer2 = get_new_weight_layer2(w_layer2, learning_rate, s_layer2, a_layer1)
print("new weight layer 2 :")
print(new_w_layer2)

new weight layer 2 :
[0.46462994 1.51379802 2.5859556 ]


In [67]:
new_bias_layer2 = get_new_bias_layer2(b_layer2, learning_rate, s_layer2)
print("new bias layer 2 :")
print(new_bias_layer2)

new bias layer 2 :
[3.24696472]


In [68]:
new_w_layer1 = get_new_weight_layer1(w_layer1, learning_rate, s_layer1)
print("new weight layer 1 :")
print(new_w_layer1)

new weight layer 1 :
[0.1 0.3 0.5]


In [69]:
new_bias_layer1 = get_new_bias_layer1(b_layer1, learning_rate, s_layer1)
print("new bias layer 1 :")
print(new_bias_layer1)

new bias layer 1 :
[ 0.74525102  0.25543479 -0.35916614]


## Loop Computing

In [70]:
# Open a text file for writing the results
with open("/Users/twomac/Documents/Two/AIT/ISE/AI & Neuro-Fuzzy/Computing/mid/2004/result-mlp-approximate-2004.txt", "w") as file:
    for i in range(len(p)):
        file.write(f"------------- Iteration P {i+1} -------------\n")
        
        a_layer1 = np.round(get_a_layer1(p[i], w_layer1, b_layer1), 4)
        file.write("s layer 1 :\n")
        file.write(np.array_str(a_layer1) + "\n\n")

        a_layer2 = np.round(get_a_layer2(a_layer1, w_layer2, b_layer2), 4)
        file.write("a layer 2 :\n")
        file.write(np.array_str(a_layer2) + "\n\n")

        error_layer1 = np.round(get_error(t[i], a_layer2), 4)
        file.write("error layer 1 :\n")
        file.write(np.array_str(error_layer1) + "\n\n")

        s_layer2 = np.round(get_s_layer2(error_layer1), 4)
        file.write("s layer 2 :\n")
        file.write(np.array_str(s_layer2) + "\n\n")

        identity_matrix = get_identity(a_layer1)
        file.write("Identity matrix :\n")
        file.write(np.array_str(identity_matrix) + "\n\n")

        s_layer1 = np.round(get_s_layer1(identity_matrix, w_layer2, s_layer2), 4)
        file.write("s layer 1 :\n")
        file.write(np.array_str(s_layer1) + "\n\n")

        new_w_layer2 = np.round(get_new_weight_layer2(w_layer2, learning_rate, s_layer2, a_layer1), 4)
        file.write("new weight layer 2 :\n")
        file.write(np.array_str(new_w_layer2) + "\n\n")

        new_bias_layer2 = np.round(get_new_bias_layer2(b_layer2, learning_rate, s_layer2), 4)
        file.write("new bias layer 2 :\n")
        file.write(np.array_str(new_bias_layer2) + "\n\n")

        new_w_layer1 = np.round(get_new_weight_layer1(w_layer1, learning_rate, s_layer1), 4)
        file.write("new weight layer 1 :\n")
        file.write(np.array_str(new_w_layer1) + "\n\n")

        new_bias_layer1 = np.round(get_new_bias_layer1(b_layer1, learning_rate, s_layer1), 4)
        file.write("new bias layer 1 :\n")
        file.write(np.array_str(new_bias_layer1) + "\n\n")

        w_layer2 = new_w_layer2
        b_layer2 = new_bias_layer2
        
        w_layer1 = new_w_layer1
        b_layer1 = new_bias_layer1


In [71]:
with open("/Users/twomac/Documents/Two/AIT/ISE/AI & Neuro-Fuzzy/Computing/mid/2004/result-mlp-approximate-2004.txt", "r") as file:
    print(file.read())

------------- Iteration P 1 -------------
s layer 1 :
[0.7109 0.6457 0.5498]

a layer 2 :
[7.6517]

error layer 1 :
[-37.6517]

s layer 2 :
[75.3034]

Identity matrix :
[[0.20552119 0.         0.        ]
 [0.         0.22877151 0.        ]
 [0.         0.         0.24751996]]

s layer 1 :
[15.4764 34.4545 55.9173]

new weight layer 2 :
[0.4647 1.5138 2.586 ]

new bias layer 2 :
[3.247]

new weight layer 1 :
[0.1 0.3 0.5]

new bias layer 1 :
[ 0.7452  0.2555 -0.3592]

------------- Iteration P 2 -------------
s layer 1 :
[1. 1. 1.]

a layer 2 :
[7.8115]

error layer 1 :
[-7.8115]

s layer 2 :
[15.623]

Identity matrix :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

s layer 1 :
[0. 0. 0.]

new weight layer 2 :
[0.3085 1.3576 2.4298]

new bias layer 2 :
[3.0908]

new weight layer 1 :
[0.1 0.3 0.5]

new bias layer 1 :
[ 0.7452  0.2555 -0.3592]


